project_id = "woakvdhlpludrttjixxq"

[functions.send-invitation]
verify_jwt = false

[functions.send-mention-notification]
verify_jwt = true

[functions.refresh-dropbox-token]
verify_jwt = false

[functions.transcode-audio]
runtime = "node"
verify_jwt = false

[functions.validate-invitation]
verify_jwt = false

[functions.use-invitation]
verify_jwt = false
