project_id = "woakvdhlpludrttjixxq"

[functions.send-invitation]
verify_jwt = false

[functions.send-mention-notification]
verify_jwt = false  

[functions.refresh-dropbox-token]
verify_jwt = false

[functions.transcode-audio]
# runtime = "node" 
verify_jwt = false

[functions.validate-invitation]
verify_jwt = false

[functions.use-invitation]
verify_jwt = false

[functions.r2-upload]
verify_jwt = true

[functions.track-url]
verify_jwt = true

[functions.r2-transfer]
verify_jwt = true

[functions.fix-r2-metadata]
verify_jwt = true
